package com.jrx.tjp.mybatis.mapper;

import com.jrx.tjp.mybatis.entity.User;
import org.apache.ibatis.annotations.*;

import java.util.List;

/**
 * 用户Mapper接口
 *
 * @author zwg
 * @create 2018-03-15 9:33
 */
@Mapper
public interface UserMapper {

    @Delete("drop table user if exists")
    void dropTable();

    @Insert("create table user (id int generated by default as identity, age integer, name varchar(20), primary key (id))")
    void createTable();

    @Insert("insert into user(name,age) values(#{name},#{age})")
    @Options(useGeneratedKeys=true, keyProperty="id")
    void insert(User user);

    @Select("select id,name,age from user")
    List<User> findAll();

    @Select("select id,name,age from user where name like #{name}")
    List<User> findByNameLike(String name);

    /**
     * 根据用户名称获取用户对象
     * sql语句通过单独的构建类提供
     * @param name
     * @return
     */
    @SelectProvider(type = UserSqlBuilder.class,method = "getUserByName")
    User findByName(String name);

    /**
     * 根据用户名称获取用户对象
     * 通过配置文件获取sql语句
     * @param name
     * @return
     */
    User selectByName(String name);

    @Delete("delete from user")
    void deleteAll();

}
